apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: java-frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-frontend
  template:
    metadata:
      labels:
        app: java-frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret