apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Argo CD at /argo (served by argocd-server in argocd ns)
          - path: /argo(.*)
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
          # App at /java-test
          - path: /java-test(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80