apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /java-test(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-svc       # 👈 matches your Service name
                port:
                  number: 8080           # 👈 match frontend container/service port
