apiVersion: v1
kind: Service
metadata:
name: {{ .Values.mysql.serviceName }}
namespace: {{ .Values.namespace }}
spec:
selector:
app: mysql
ports:
- protocol: TCP
port: 3306
targetPort: 3306
type: ClusterIP