server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: devopslogs.com
        paths:
          - path: /argo(/|$)(.*)
            pathType: ImplementationSpecific
    tls: [] # Add cert-manager or ACM if you want TLS automation

  # Critical for UI path
  extraArgs:
    - --basehref
    - /argo
