global:
  domain: devopslogs.com

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - devopslogs.com
    paths:
      - /argo(/|$)(.*)
    pathType: Prefix
    extraAnnotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

configs:
  params:
    server.basehref: /argo
