global:
  domain: devopslogs.com

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - devopslogs.com
    paths:
      - /argo       # keep ingress path prefix
    pathType: Prefix
    extraAnnotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

configs:
  params:
    server.basehref: /   # ✅ ArgoCD should think it runs at /
