global:
  domain: devopslogs.com

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - devopslogs.com
    paths:
      - /argo          # ArgoCD path
    pathType: Prefix
    extraAnnotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # Do NOT use rewrite-target here

configs:
  params:
    server.basehref: /argo  # IMPORTANT: tells ArgoCD it runs under /argo
