apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minj1992/argo-cd.git
    targetRevision: HEAD
    path: charts/java-webapp
  helm:
    values: |
      image:
        frontend: 180294213274.dkr.ecr.us-east-1.amazonaws.com/app001-dev:frontend1.1.0
        mysql: 180294213274.dkr.ecr.us-east-1.amazonaws.com/app001-dev:backend1.1.0
      ingress:
        host: devopslogs.com
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true